---
Namespace: Delphinus.OTAPI
CustomSerializers:
  byte[]: OTAPISerialization.Serialize(writer, value)
  ushort[]: OTAPISerialization.Serialize(writer, value)
  short[]: OTAPISerialization.Serialize(writer, value)
  Vector2: OTAPISerialization.Serialize(writer, value)
  Color: OTAPISerialization.Serialize(writer, value)
  BitsByte: OTAPISerialization.Serialize(writer, value)
  MultiToolMode: OTAPISerialization.Serialize(writer, value)
  NetworkText: OTAPISerialization.Serialize(writer, value)
  PlayerDeathReason: OTAPISerialization.Serialize(writer, value)
  PlayerSpawnContext: OTAPISerialization.Serialize(writer, value)
  NetModuleType: OTAPISerialization.Serialize(writer, value)
  MessageID: OTAPISerialization.Serialize(writer, value)
CustomDeserializers:
  byte[]: OTAPISerialization.SerializeBytes(reader)
  ushort[]: OTAPISerialization.DeserializeUInt16Array(reader)
  short[]: OTAPISerialization.DeserializeInt16Array(reader)
  Vector2: OTAPISerialization.DeserializeVector2(reader)
  Color: OTAPISerialization.DeserializeColor(reader)
  BitsByte: OTAPISerialization.DeserializeBitsByte(reader)
  MultiToolMode: OTAPISerialization.DeserializeMultiToolMode(reader)
  NetworkText: OTAPISerialization.DeserializeNetworkText(reader)
  PlayerDeathReason: OTAPISerialization.DeserializePlayerDeathReason(reader)
  PlayerSpawnContext: OTAPISerialization.DeserializePlayerSpawnContext(reader)
  NetModuleType: OTAPISerialization.DeserializeNetModuleType(reader)
  MessageID: OTAPISerialization.DeserializeMessageID(reader)
UsingStatements:
  - using System.IO;
  - using Microsoft.Xna.Framework;
  - using Terraria;
  - using Terraria.Localization;
  - using Terraria.DataStructures;
  - using static Terraria.GameContent.UI.WiresUI.Settings;
